language: elixir
otp_release:
  - 18.3
  - 19.0
  - 20.0
elixir:
  - 1.4
  - 1.5
env: MIX_ENV=test
install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix do deps.get, compile
  - mix ecto.create
notifications:
  email:
    - paulschoenfelder@gmail.com
